/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class App {
    public static void main(String[] args) {
        
        Pessoa p1 = new Pessoa("Adrian", 21);
        
        p1.apresentar();
        
        Animal a1 = new Animal("bolinha",10, "carnivoro", Sexo.FEMEA); 
	Animal a2 = new Animal("Bidu", 10, "carnivoro", Sexo.MACHO);
	
	if (a1.podemReproduzir(a2)) {
		Animal a3 = a1.reproduzir(a2);
		a3.info();
	} else {
		System.out.println("Não conseguem reproduzir");
	}
        /* Operadores aritméticos
        
        double soma = 4 + 2;
        double sub = 4 - 2;
        double mult = 4 * 2;
        double div = 4 / 2;
        double mod = 4 % 2;
        
        System.out.println(soma);
        System.out.println(sub);
        System.out.println(mult);
        System.out.println(div);
        System.out.println(mod);
        
        */
        /* Operadores de comparação
        
        System.out.println(n1 == n2);
        System.out.println(n1 != n2);
        System.out.println(n1 > n2);
        System.out.println(n1 >= n2);
        System.out.println(n1 < n2);
        System.out.println(n1 <= n2);
        */
        
        /* ´Operadores lógicos
        System.out.println(true && true); // true
        System.out.println(false && true); // false
        System.out.println(false && false); // false
        
        System.out.println(false || true); // true
        System.out.println(false || true); // true
        System.out.println(false || true); // true
        
        System.out.println(!false); // true
        System.out.println(!true); // false
        
        */
        
        /* IF ELSE
        int idade = 21;
        boolean maioridade = idade > 17;
        boolean temCarteira = true;
        
        if (maioridade && temCarteira) {
            System.out.println("Voce pode dirigir");
        } else if(maioridade) {
            System.out.println("Voce e de maior, mas não pode dirigir.");
        } else {
            System.out.println("Voce e de menor não pode dirigir.");
        }
        
         SWITCH CASE 
        
        String time = "gremio";
        
        switch(time) {
                case "gremio":
                         System.out.println("E o gremio");
                break;
                
                case "inter":
                        System.out.println("E o inter");
                break;
                
                default:
                        System.out.println("Algum time ne");
                break;
        }
        
        // LOOPS
        
        int voltas = 0;
        
        while (voltas < 11) {
                System.out.println("Voce ja pedalou " + voltas + " voltas!");
                voltas++;
        }
        
        for (int contagem = 0; contagem <= 10; contagem++) {   
                System.out.println(contagem);
        }
        
        */
    }
}
